"""Validate example instrument records and rebuild fleet-wide inventory views."""

import csv
import sys
from pathlib import Path

import yaml

EXAMPLE_DIR = Path(__file__).resolve().parent.parent
INSTRUMENTS_DIR = EXAMPLE_DIR / "instruments"
DERIVED_DIR = EXAMPLE_DIR / "derived"
STATUSES = {"active", "repair", "retired"}
CSV_FIELDS = (
    "key",
    "type",
    "serial",
    "nickname",
    "status",
    "owner_team",
    "site",
    "room",
    "bench",
    "declared_version",
    "commissioned_on",
)


def load_records() -> list[dict[str, str]]:
    records = []
    seen_keys = set()
    for path in sorted(INSTRUMENTS_DIR.glob("*/*/instrument.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{path}: expected a YAML mapping")

        for field in ("key", "type", "serial", "status", "owner_team"):
            if not isinstance(data.get(field), str) or not data[field].strip():
                raise ValueError(f"{path}: {field} must be a non-empty string")

        expected_key = f"{data['type']}/{data['serial']}"
        if data["key"] != expected_key:
            raise ValueError(f"{path}: key must be {expected_key!r}")
        if path.parent.name != data["serial"] or path.parent.parent.name != data["type"]:
            raise ValueError(f"{path}: folder names must match type and serial")
        if data["status"] not in STATUSES:
            raise ValueError(f"{path}: status must be one of {', '.join(sorted(STATUSES))}")

        folded_key = data["key"].casefold()
        if folded_key in seen_keys:
            raise ValueError(f"{path}: duplicate permanent key {data['key']!r}")
        seen_keys.add(folded_key)

        location = data.get("location")
        software = data.get("software")
        hardware = data.get("hardware")
        if not isinstance(location, dict) or not isinstance(software, dict) or not isinstance(hardware, dict):
            raise ValueError(f"{path}: location, software, and hardware must be mappings")
        for field in ("site", "room"):
            if not isinstance(location.get(field), str) or not location[field].strip():
                raise ValueError(f"{path}: location.{field} must be a non-empty string")
        for field, value in (
            ("software.declared_version", software.get("declared_version")),
            ("hardware.commissioned_on", hardware.get("commissioned_on")),
        ):
            if value is None or isinstance(value, (dict, list)) or not str(value).strip():
                raise ValueError(f"{path}: {field} must be present")

        records.append(
            {
                "key": data["key"],
                "type": data["type"],
                "serial": data["serial"],
                "nickname": data.get("nickname", ""),
                "status": data["status"],
                "owner_team": data["owner_team"],
                "site": location["site"],
                "room": location["room"],
                "bench": location.get("bench", ""),
                "declared_version": str(software["declared_version"]),
                "commissioned_on": str(hardware["commissioned_on"]),
            }
        )
    if not records:
        raise ValueError(f"No instrument.yaml records found under {INSTRUMENTS_DIR}")
    return records


def write_csv(records: list[dict[str, str]]) -> None:
    path = DERIVED_DIR / "master-instrument-list.csv"
    with path.open("w", newline="", encoding="utf-8") as output:
        writer = csv.DictWriter(output, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(records)


def write_markdown(records: list[dict[str, str]]) -> None:
    path = DERIVED_DIR / "master-instrument-list.md"
    columns = ("key", "nickname", "status", "owner_team", "site", "room", "declared_version")
    lines = [
        "<!-- Generated by scripts/build_master_list.py; edit instrument records instead. -->",
        "# Master instrument list",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for record in records:
        values = [record[column].replace("|", "\\|") for column in columns]
        lines.append("| " + " | ".join(values) + " |")
    lines.extend(("", f"Total instruments: {len(records)}", ""))
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    try:
        records = load_records()
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f"Cannot build master list: {error}", file=sys.stderr)
        return 1

    DERIVED_DIR.mkdir(parents=True, exist_ok=True)
    write_csv(records)
    write_markdown(records)
    print(f"Validated {len(records)} instruments; wrote CSV and Markdown views to {DERIVED_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
